# Generated by Django 4.2.7 on 2025-11-23 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('citoyen', 'Citoyen'), ('admin_public', 'Administration Publique'), ('admin_plateforme', 'Administrateur Plateforme')], default='citoyen', max_length=20, verbose_name='Rôle'),
        ),
    ]
